### ISSUE TITLE
Should be able to get the images if the engine is imported.

### ISSUE THREAD

**Issue by akosgarai** [akosgarai/playground_engine#21]
```
akosgarai@akos-szemetlada ~/Documents/golang/src/github.com/akosgarai/opengl_playground (deattach-engine*) $ go run examples/08-multiple-light/app.go
OpenGL version 4.1.0 NVIDIA 440.82
panic: open /home/akosgarai/Documents/golang/src/github.com/akosgarai/opengl_playground/examples/08-multiple-light/assets/metal.jpg: no such file or directory

goroutine 1 [running, locked to thread]:
github.com/akosgarai/playground_engine/pkg/texture.(*Textures).AddTexture(0xc0000c1278, 0xc0000e8000, 0x77, 0x812f0000812f, 0x260100002601, 0x6448f6, 0x10, 0x683d80, 0xa21b08)
	/home/akosgarai/Documents/golang/pkg/mod/github.com/akosgarai/playground_engine@v0.0.0-20200611154221-10f4a9d15314/pkg/texture/texture.go:65 +0x6ad
github.com/akosgarai/playground_engine/pkg/model.NewTexturedStreetLamp(0xc0c000003ecccccd, 0x40c00000bfa66666, 0x683d80, 0xa21b08, 0x7000a82a0)
	/home/akosgarai/Documents/golang/pkg/mod/github.com/akosgarai/playground_engine@v0.0.0-20200611154221-10f4a9d15314/pkg/model/streetlamp.go:88 +0x126
main.TexturedStreetLamp(0xc0c000003ecccccd, 0xc0bfa66666, 0xc0000c1788)
	/home/akosgarai/Documents/golang/src/github.com/akosgarai/opengl_playground/examples/08-multiple-light/app.go:115 +0x5d
main.main()
	/home/akosgarai/Documents/golang/src/github.com/akosgarai/opengl_playground/examples/08-multiple-light/app.go:244 +0x1ccb
exit status 2
```

**Comment by akosgarai** [comment]
might be related: https://stackoverflow.com/questions/44275403/how-to-get-path-of-imported-package

**Comment by akosgarai** [comment]
cli tool for installing models to the current application?

**Comment by akosgarai** [comment]
The idea: Implement a CLI tool for the playground_engine. I need to be able to download / install the shaders, textures, necessary obj, material files, etc.
something like:
```
playgorund install texture-shader
```
Should download the vertex & fragment shaders for the textured objects, and put them into a relevant directory. The downloaded and the original dir. structure should be the same.
